import assert from 'node:assert/strict';
import prisma from '../config/prisma.js';
import { createTicket } from '../services/helpdesk.service.js';
import { completeTraining } from '../services/training.service.js';
import { submitQuizAttempt } from '../services/quiz.service.js';
import { acknowledgePolicy } from '../services/policy.service.js';
const notifications = [];
let queriedRole;
prisma.user.findUnique = async () => ({ firstName: 'Test', lastName: 'Employee', role: 'EMPLOYEE' });
prisma.user.findMany = async ({ where }) => { assert.equal(where.isActive, true); queriedRole = where.role; return [{ id: where.role }]; };
prisma.notification.createMany = async ({ data }) => { notifications.push(...data); return { count: data.length }; };
prisma.helpdeskTicket.create = async () => ({ id: 'ticket', subject: 'Help', priority: 'HIGH' });
await createTicket({ creatorId: 'employee', subject: 'Help', description: 'Issue' });
assert.equal(queriedRole, 'SYSTEM_ADMIN');
assert.equal(notifications.at(-1).resourceRef, 'ticket');
assert.equal(notifications.at(-1).isRead, false);
prisma.trainingModule.findUnique = async () => ({ id: 'module', title: 'Training', isPublished: true });
let progress = null;
prisma.trainingProgress.findUnique = async () => progress;
prisma.trainingProgress.create = async ({ data }) => (progress = { id: 'progress', ...data });
prisma.trainingProgress.update = async ({ data }) => (progress = { ...progress, ...data });
await completeTraining('module', 'employee');
assert.equal(queriedRole, 'TRAINING_ADMIN');
let count = notifications.length;
await completeTraining('module', 'employee');
assert.equal(notifications.length, count);
progress = { id: 'progress', status: 'IN_PROGRESS' };
await completeTraining('module', 'employee');
assert.equal(notifications.length, count + 1);
prisma.quizAttempt.findUnique = async () => ({ id: 'attempt', userId: 'employee', quizId: 'quiz', answers: [] });
prisma.quiz.findUnique = async () => ({ title: 'Quiz', passingScore: 70, questions: [{ id: 'q', points: 1, options: [{ id: 'yes', isCorrect: true }, { id: 'no', isCorrect: false }] }] });
prisma.$transaction = async fn => fn({ quizAnswer: { createMany: async () => ({ count: 1 }) }, quizAttempt: { update: async () => ({ id: 'attempt', quizId: 'quiz', attemptNumber: 1 }) } });
for (const [option, type] of [['yes', 'QUIZ_PASSED'], ['no', 'QUIZ_FAILED']]) {
 await submitQuizAttempt('quiz', 'attempt', 'employee', [{ questionId: 'q', selectedOptionId: option }]);
 assert.equal(queriedRole, 'TRAINING_ADMIN');
 assert.equal(notifications.at(-1).type, type);
}
prisma.policy.findUnique = async () => ({ id: 'policy', title: 'Policy', status: 'PUBLISHED', versions: [{ id: 'version', versionNumber: 2 }] });
prisma.auditLog.findFirst = async () => null;
let ack = null;
prisma.policyAcknowledgement.findUnique = async () => ack;
prisma.policyAcknowledgement.create = async ({ data }) => (ack = data);
await acknowledgePolicy('policy', { id: 'employee' });
assert.equal(queriedRole, 'COMPLIANCE_OFFICER');
assert.match(notifications.at(-1).message, /version 2/);
count = notifications.length;
await acknowledgePolicy('policy', { id: 'employee' });
assert.equal(notifications.length, count);
prisma.user.findUnique = async () => ({ role: 'SYSTEM_ADMIN' });
await createTicket({ creatorId: 'admin', subject: 'Help', description: 'Issue' });
assert.equal(notifications.length, count);
console.log('Employee action notifications passed: ticket, training create/update/repeat, quiz pass/fail, acknowledgement/repeat, and role targeting.');
await prisma.$disconnect();
